service: serverless-node
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
# you can overwrite defaults here
  stage: dev
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
     - http: ANY /{proxy+}
     - http: ANY /